//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StockMon.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ROWLISTYPE                  129
#define ID_MESSAGE_INDICATOR            129
#define IDB_STATEICONS                  130
#define IDB_BBB_LOGO                    138
#define IDB_UPARROW                     140
#define IDB_DOWNARROW                   141
#define IDR_NOARROW                     142
#define IDB_ARROWS                      143
#define IDB_SMALL_ARROWS                143
#define IDD_OPTIONS                     144
#define IDB_LARGE_ARROWS                144
#define IDD_CONFIRM_DEL_DLG             145
#define IDR_POPUP_MENU                  150
#define IDD_CONFIG_ALERT_DLG            150
#define IDD_SET_ALERT_DLG               151
#define IDB_BITMAP1                     153
#define IDR_LOCKED                      158
#define IDR_UPARROW                     162
#define IDD_PREF_CHART_DLG              162
#define IDR_DOWNARROW                   164
#define IDD_REGISTER_DLG                164
#define IDD_TRADE_DLG                   167
#define IDD_TRADE_DETAILS_DLG           168
#define IDD_TECH_CHART_DLG              169
#define IDD_STK_SCREEN_DLG              171
#define IDD_PREF_GENERAL                174
#define IDD_VALUATION_DLG               181
#define IDD_PREF_UPDATES                183
#define IDD_PREF_RGB                    184
#define IDD_PREF_PROXY                  191
#define IDC_SYMBOLS                     1000
#define ID_UPDATES_INTERVAL             1001
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_LAST                        1003
#define IDC_SCR_PS_RATIO_MIN            1003
#define IDC_CHANGE                      1004
#define IDC_SCR_PS_RATIO_MAX            1004
#define IDC_HIGH                        1005
#define IDC_SCR_PRICE_MIN               1005
#define IDC_LOW                         1006
#define IDC_SCR_PRICE_MAX               1006
#define IDC_VOLUME                      1007
#define IDC_LASTUPDATED                 1008
#define IDC_APPLY                       1009
#define IDC_VIEW_FRACTIONS              1010
#define ID_PROXY_HOST                   1011
#define IDC_VIEW_DECIMALS               1011
#define ID_PROXY_PORT                   1012
#define ID_PROXY_USE_PROXY              1013
#define IDC_CHART_PTS                   1013
#define IDC_SCR_BETA_MIN                1013
#define IDC_CHART_TYPE                  1014
#define IDC_SCR_BETA_MAX                1014
#define D_GEN_CONFIRM_DEL               1015
#define IDC_SCR_YIELD_MIN               1015
#define IDC_CHART_LOC                   1016
#define IDC_SCR_YIELD_MAX               1016
#define IDC_CHART_STRING                1016
#define ID_GEN_AUTO_SAVE_DOC            1017
#define IDC_SCR_PE_MIN                  1017
#define IDC_CHART_LOC2                  1017
#define IDC_AUTH_KEY                    1018
#define IDC_SCR_PE_MAX                  1018
#define IDC_SCR_EPS_CHG_MIN             1019
#define IDC_REG_INSTRUCTIONS            1020
#define IDC_SCR_EPS_CHG_MAX             1020
#define IDC_SELECT_WAV_FILE             1021
#define IDC_REGISTER_KEY                1021
#define IDC_SCR_GR_MIN                  1021
#define IDC_SCR_GR_MAX                  1022
#define IDC_SCR_ROE_MIN                 1023
#define IDC_MESSAGE                     1024
#define IDC_SCR_ROE_MAX                 1024
#define IDC_ALERT_SECONDS               1025
#define IDC_PORTFOLIO                   1025
#define IDC_SHARES                      1026
#define IDC_COMMISION                   1027
#define IDC_SCR_DP_MIN                  1027
#define IDC_SCR_DP_MAX                  1028
#define IDC_DAY_LOW                     1029
#define IDC_DAY_HI                      1030
#define IDC_DATE                        1031
#define IDC_PRICE                       1032
#define IDC_AMOUNT                      1033
#define IDC_SCR_DE_MIN                  1033
#define IDC_BUY                         1034
#define IDC_SCR_DE_MAX                  1034
#define IDC_SELL                        1035
#define IDC_SCR_SALES_MIN               1035
#define IDB_APPLY                       1036
#define IDC_SCR_SALES_MAX               1036
#define IDC_SCR_MKTCAP_MIN              1037
#define IDC_TRADE_DTLS                  1038
#define IDC_SCR_MKTCAP_MAX              1038
#define IDB_TRADE                       1039
#define IDC_TICKER_LB                   1040
#define IDC_EXP_MA_1                    1042
#define IDC_EXP_MA_2                    1043
#define IDC_EXP_MA_3                    1044
#define IDC_TIME_HORIZON                1045
#define IDC_OBV_RB                      1048
#define IDC_STOC_RB                     1049
#define IDC_STOC_VALUE                  1050
#define IDC_WILDER_RSI_RB               1051
#define IDC_MACD_RB                     1052
#define IDC_PRICE_ROC_RB                1053
#define IDC_RSI_VALUE                   1054
#define IDC_MACD_VALUE                  1055
#define IDC_PRICE_ROC_VALUE             1056
#define IDC_VOLUME_RB                   1058
#define IDC_LOG_SCALE                   1060
#define ID_GET_CHART                    1061
#define IDC_SCR_PB_RATIO_MIN            1062
#define IDC_SCR_PB_RATIO_MAX            1063
#define IDC_DJ                          1064
#define IDC_SP500                       1068
#define IDC_INDUSTRY_GRP                1069
#define IDC_EXCHANGES                   1070
#define IDC_MODEM                       1072
#define IDC_DUP                         1073
#define IDC_NEWCONN                     1074
#define IDC_HANGUP                      1076
#define IDC_USEEXISTING                 1077
#define IDC_VAL_TICKER                  1078
#define IDC_VAL_NEXT_YR_EPS             1079
#define IDC_BUILD_DATE                  1079
#define IDC_VAL_EST_PRICE               1080
#define IDC_PREF_RGB_ROE_LBL            1080
#define IDC_VAL_BUY_BELOW               1081
#define IDC_VAL_LAST_QUOTE              1082
#define IDC_VAL_VALUATION               1083
#define IDC_VAL_PROJ_5YR_GROWTH         1084
#define IDC_VAL_CGI                     1085
#define IDC_VAL_UPD_PE                  1088
#define IDC_VAL_UPD_NEXT_YR_EPS         1089
#define IDC_VAL_UPD_EARN_GRWTH          1090
#define IDC_VAL_PE                      1091
#define IDC_CHARTSTRING                 1092
#define ID_GEN_UPPER_CASE               1098
#define ID_UPDATE_OPEN                  1100
#define ID_UPDATE_CLOSE                 1101
#define ID_UPDATE_DISABLE_AUTO          1113
#define ID_UPDATES_ENABLE_ALWAYS        1114
#define ID_UPDATES_ENABLE_MKT_HRS       1115
#define ID_UPDATES_NO_WKENDS            1182
#define IDC_ALERT_NO_ALERT              2000
#define IDC_ALERT_FLASH_WND             2001
#define IDC_ALERT_WND_TOP               2002
#define IDC_ALERT_BEEP                  2003
#define IDC_ALERT_PLAY_WAV              2004
#define IDC_ALERT_FREQ_ONCE             2005
#define IDC_ALERT_REPEAT                2006
#define IDB_SMALLICONS                  26018
#define IDB_LARGEICONS                  26019
#define ID_VIEW_LARGEICONS              32771
#define ID_VIEW_SMALLICONS              32772
#define ID_VIEW_ROWDETAILS              32775
#define ID_STOP_UPDATES                 32775
#define ID_VIEW_STATEICONS              32782
#define ID_VIEW_CLIENTWIDTHSEL          32788
#define ID_VIEW_REFRESH                 32789
#define ID_VIEW_OPTIONS                 32790
#define ID_FILES_SAVEAS                 32791
#define ID__UPDATE                      32799
#define ID__DELETE                      32800
#define ID_PORTFOLIO_ADDTICKER          32801
#define ID_PORTFOLIO_DELETETICKER       32802
#define ID_PORTFOLIO_UPDATESELECTED     32803
#define ID_PORTFOLIO_ADDINDEXTICKERS_NASDAQCOMPOSITE 32808
#define ID_PORTFOLIO_ADDINDEXTICKERS_DJIA 32809
#define ID_PORTFOLIO_ADDINDEXTICKERS_SP500 32810
#define ID_PORTFOLIO_ADDINDEXTICKERS_NYSECOMPOSITE 32811
#define ID_PORTFOLIO_ADDINDEXTICKERS_AMEXMARKETVALUE 32812
#define ID_PORTFOLIO_ADDINDEXTICKERS_SP100 32813
#define ID_PORTFOLIO_ADDINDEXTICKERS_RUSSEL2000 32814
#define ID_PORTFOLIO_ADDINDEXTICKERS_MAJORMARKETINDEX 32815
#define ID_PORTFOLIO_ADDINDEXTICKERS_VALUELINECOMPOSITE 32816
#define ID_PORTFOLIO_ADDINDEXTICKERS_WILSHIRESMALLCAP 32817
#define ID_PORTFOLIO_ADDINDEXTICKERS_ADDALLOFTHEABOVE 32818
#define ID_PORTFOLIO_ADDINDEXTICKERS_REMOVEALLOFTHEABOVE 32819
#define ID_PORTFOLIO_ALERT              32820
#define ID_SUMMARY_NASDAQ               32821
#define ID_SUMMARY_CLOSE                32822
#define ID_SUMMARY_NYSE                 32823
#define ID_SUMMARY_AMEX                 32824
#define ID_VIEW_MKT_SUMMARY             32825
#define ID_VIEW_VIEWQUOTES              32826
#define ID_PORTFOLIO_GETSELECTEDGRAPH   32829
#define ID_PORTFOLIO_COMP_CHARTS        32830
#define ID_PORTFOLIO_ADDFUND            32834
#define ID_VIEW_REFRESHGRAPHS           32835
#define ID_HELP_HOWTOREGISTER           32836
#define ID_PORTFOLIO_TRADE              32837
#define ID_CHARTS_TECHNICALCHARTING     32838
#define ID_CHARTS_GETSELECTEDTECHNICALCHARTS 32839
#define ID_CHARTS_GETALLTECHNICALCHARTS 32840
#define ID_PORTFOLIO_SCREEN             32841
#define ID_VIEW_VIEWSCREENING           32842
#define ID_GETTECHNICALCHART_VOLUME     32843
#define ID_GETTECHNICALCHART_ONBALANCEVOLUME 32844
#define ID_GETTECHNICALCHART_STOCHASTICS 32845
#define ID_GETTECHNICALCHART_WILDERSRSI 32846
#define ID__GETTECHNICALCHART_MACD      32847
#define ID_GETTECHNICALCHART_PRICERATEOFCHANGE 32848
#define ID_GETTECHNICALCHART_GETALLOFTHEABOVE 32849
#define ID_PORTFOLIO_GETCOMPANYNAMES    32850
#define ID_PORTFOLIO_GETCOMPANYFUNDAMENTALS 32851
#define ID_VIEW_VIEWFUNDAMENTALS        32852
#define ID_MENUITEM32853                32853
#define ID_MENUITEM32854                32854
#define ID_GETTECHNICALCHART_GETALLOFTHEABOVEANDMERGE 32855
#define ID_GETTECHNICALCHART_MERGEALLCHARTS 32856
#define ID_VIEW_MYLIST                  32857
#define ID_CHART_5MIN                   32858
#define ID_CHART_DAILY                  32859
#define ID_CHART_WEEKLY                 32860
#define ID_PORTFOLIO_VALUATION          32861
#define ID_VIEW_VIEWVALUATIONS          32862
#define ID__VALUATION                   32863
#define ID_VIEW_REFRESHVALUATION        32864
#define ID_CHART_MONTLY                 32865
#define ID_CHART_MONTHLY                32867
#define ID_BROWSER_STOP                 32868
#define ID_BROWSER_BACK                 32869
#define ID_BROWSER_FORWARD              32870
#define ID_BROWSER_REFRESH              32871
#define ID_FAVORITES                    32872
#define ID_VIEW_VIEWBROWSER             32874
#define ID_PORTFOLIO_GETNEWS            32875
#define ID_BUTTON32877                  32877
#define ID_PORTFOLIO_SORT_ALERT_CLOSESTTOLOWPRICE 32878
#define ID_PORTFOLIO_SORT_ALERT_CLOSESTTOHIGHPRICE 32879
#define ID_PORTFOLIO_DELOVERVALUED      32880
#define ID_CHART_YAHOO_ONE_DAY          32882
#define ID_CHART_YAHOO_5_DAY            32883
#define ID_CHART_YAHOO_3_MONTH          32884
#define ID_CHART_YAHOO_6_MONTH          32885
#define ID_CHART_YAHOO_1_YEAR           32886
#define ID_CHART_YAHOO_2_YEAR           32887
#define ID_CHART_YAHOO_5_YEAR           32888
#define ID_CHART_YAHOO_MAX              32889
#define ID_FILE_IMPORT                  32890
#define ID_SUMMARY_YAHOONYSE_VOLUMELEADERS 32893
#define ID_SUMMARY_YAHOONYSE_PRICEGAINERS 32894
#define ID_SUMMARY_YAHOONASDAQ_VOLUMELEADERS 32895
#define ID_SUMMARY_YAHOONASDAQ_PRICEGAINERS 32896
#define ID_SUMMARY_YAHOOAMEX_VOLUMELEADERS 32897
#define ID_SUMMARY_YAHOOAMEX_PRICEGAINERS 32898
#define ID_SUMMARY_YAHOOALLVOLUMEGAINERS 32899
#define ID_SUMMARY_YAHOOALLPRICEGAINERS 32900
#define ID_SUMMARY_YAHOOALL             32901
#define ID_SUMMARY_INDIAALLVOLUMEGAINERS 32902
#define ID_SUMMARY_INDIAALLPRICEGAINERS 32903
#define ID_SUMMARY_WSJALL               32904
#define ID_SUMMARY_WSJSUMMARY           32905
#define ID_CHART_TYPE_LINE              32906
#define ID_CHART_TYPE_BAR               32907
#define ID_CHART_TYPE_CANDLE            32908
#define ID_FILE_EXPORT                  32911
#define ID_PORTFOLIO_DELETEALLTRADES    32913
#define ID_PORTFOLIO_INITTRADES         32914
#define ID_PORTFOLIO_EXPORT             32915
#define ID_FILE_IMPORT_ISM              32917
#define ID_VIEW_VIEWRBG                 32918
#define ID_PORTFOLIO_RGB                32919
#define ID_PORTFOLIO_NOTES              32920
#define ID_Menu                         32921
#define ID_VIEW_REFRESHRGB              32922
#define ID_VIEW_REFILTERRGB             32923
#define ID_CHART_SITE                   32924
#define ID_SITE_YAHOO                   32925
#define ID_SITE_TD                      32926
#define ID_TIMEFRAME_10DAY              32927
#define ID_CHART_YAHOO_10_DAY           32928
#define ID_TIMEFRAME_10DAY32929         32929
#define ID_CHART                        32930
#define ID_VIEW_REFILTERVALUATION       32933
#define ID_PORTFOLIO_GETTOPHOLDINGS     32934
#define ID_CHART_COMPAREWITH            32935
#define ID_COMPAREWITH_SP500            32936
#define ID_COMPAREWITH_NASDAQ           32937
#define ID_COMPAREWITH_DOW              32938
#define ID_COMPAREWITH_CLEAR            32939
#define ID_Menu32940                    32940
#define ID_FILE_IMPORT_TICKERS          32941
#define ID_VIEW_SHOWRECOMMENDATIONS     32942
#define IDS_OPEN_TIME                   61204
#define IDS_CLOSE_TIME                  61205
#define IDS_PROXY                       61206
#define IDS_PORT                        61207
#define IDS_IP_DBC                      61208
#define IDS_IP_MONEY                    61209
#define IDS_IP_TECHSTOCKS               61210
#define IDS_IP_TECHSTKS                 61211
#define IDS_IP_LOMBARD                  61212
#define IDS_POINTS                      61213
#define IDS_TYPES                       61214
#define IDS_NASDAQ_COMPX                61215
#define IDS_INDU                        61216
#define IDS_NYAX                        61217
#define IDS_INX                         61218
#define IDS_XAX                         61219
#define IDS_IUX                         61220
#define IDS_MMX                         61221
#define IDS_VLE                         61222
#define IDS_WSX                         61223
#define IDS_NASDAQT                     61224
#define IDS_AMEXT                       61225
#define IDS_NYSET                       61226
#define IDS_TECHSTKS_COY_NOT_FOUND      61227
#define IDS_NOT_LIC_MSG                 61229
#define IDS_OEX                         61230
#define IDS_INVALID_SER_NO_MSG          61232
#define IDS_HOW_TO_REG                  61233
#define IDS_ABOUT_LEGAL                 61234
#define IDS_ABOUT_ILLEGAL               61235
#define IDS_SMVIEW                      61236
#define IDS_SCRNVIEW                    61237
#define IDC_ALERT_SEC                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32943
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
